# Generated by Django 4.0.5 on 2022-07-24 18:22

import ascendaApp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('firstName', models.CharField(blank=True, default='', max_length=256)),
                ('lastName', models.CharField(blank=True, default='', max_length=256)),
                ('countryCode', models.CharField(blank=True, default='', max_length=256)),
                ('phoneNumber', models.CharField(blank=True, default='', max_length=256)),
                ('emailAddress', models.CharField(blank=True, default='', max_length=256)),
                ('specialRequest', models.CharField(blank=True, default='', max_length=256)),
                ('cardNumber', models.CharField(blank=True, default='', max_length=256)),
                ('nameOnCard', models.CharField(blank=True, default='', max_length=256)),
                ('expiryDate', models.DateField(default=django.utils.timezone.now)),
                ('cvvCvc', models.CharField(blank=True, default='', max_length=256)),
                ('address', models.CharField(blank=True, default='', max_length=256)),
                ('city', models.CharField(blank=True, default='', max_length=256)),
                ('zipCode', models.CharField(blank=True, default='', max_length=256)),
                ('country', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=16)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=16)),
                ('state', models.CharField(blank=True, default='', max_length=256)),
                ('term', models.CharField(blank=True, default='', max_length=256)),
                ('type', models.CharField(blank=True, default='', max_length=256)),
                ('uid', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('destination', models.CharField(blank=True, default='', max_length=256)),
                ('reviewScore', models.DecimalField(blank=True, decimal_places=5, max_digits=6)),
                ('rooms', models.IntegerField(default=0)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('customerType', models.CharField(blank=True, choices=[('B', 'Business'), ('F', 'Families'), ('C', 'Couples'), ('S', 'Singles')], default='S', max_length=2)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('lat', models.DecimalField(blank=True, decimal_places=5, max_digits=8)),
                ('lng', models.DecimalField(blank=True, decimal_places=5, max_digits=8)),
                ('reviewCount', models.JSONField(blank=True, default=ascendaApp.models.Hotel.reviewCountDefault)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['dateCreated'],
            },
        ),
    ]
