# Generated by Django 4.0.5 on 2022-06-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('reviewScore', models.DecimalField(decimal_places=5, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('address', models.CharField(max_length=256)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=5, max_digits=8)),
                ('customerType', models.CharField(max_length=64)),
            ],
        ),
    ]
