# Generated by Django 4.0.5 on 2022-07-20 03:33

import ascendaApp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ascendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['dateCreated']},
        ),
        migrations.AddField(
            model_name='hotel',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='reviewCount',
            field=models.JSONField(blank=True, default=ascendaApp.models.Hotel.reviewCountDefault),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='customerType',
            field=models.CharField(blank=True, choices=[('B', 'Business'), ('F', 'Families'), ('C', 'Couples'), ('S', 'Singles')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='reviewScore',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=6),
        ),
    ]
