# Generated by Django 4.0.5 on 2022-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascendaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=5, max_digits=8)),
                ('lng', models.DecimalField(blank=True, decimal_places=5, max_digits=8)),
                ('state', models.CharField(blank=True, default='', max_length=256)),
                ('term', models.CharField(blank=True, default='', max_length=256)),
                ('type', models.CharField(blank=True, default='', max_length=256)),
                ('uid', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
    ]
