# Generated by Django 4.0.5 on 2022-08-04 12:41

from django.db import migrations, models
import django.utils.timezone
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ascendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='address',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='cardNumber',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='country',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='countryCode',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='cvvCvc',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='emailAddress',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='expiryDate',
            field=django_cryptography.fields.encrypt(models.DateField(default=django.utils.timezone.now)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='firstName',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='lastName',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='nameOnCard',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='phoneNumber',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='specialRequest',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='title',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='zipCode',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=256)),
        ),
    ]
