# Generated by Django 4.0.5 on 2022-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascendaApp', '0002_alter_hotel_options_hotel_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
