# Generated by Django 4.0.5 on 2022-08-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascendaApp', '0002_alter_bookinginfo_address_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['term'], name='ascendaApp__term_62b1b9_idx'),
        ),
    ]
