# Generated by Django 4.0.5 on 2022-08-10 17:32

from django.db import migrations, models
import django.utils.timezone
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ascendaApp', '0003_destination_ascendaapp__term_62b1b9_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='uid',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='expiryDate',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, default=django.utils.timezone.now, max_length=256)),
        ),
    ]
