# Generated by Django 4.0.5 on 2022-07-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ascendaApp', '0003_hotel_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
    ]
