# Generated by Django 4.0.5 on 2022-07-22 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ascendaApp', '0003_bookinginfo'),
        ('ascendaApp', '0004_hotel_rooms'),
    ]

    operations = [
    ]
