import React from "react";
import MenuItem from '@mui/material/MenuItem';

export default function CountryCodes() {

  return <div>
    <MenuItem className='menuItem' value={1}>+7</MenuItem>
    <MenuItem className='menuItem' value={2}>+20</MenuItem>
    <MenuItem className='menuItem' value={3}>+27</MenuItem>
    <MenuItem className='menuItem' value={4}>+30</MenuItem>
    <MenuItem className='menuItem' value={5}>+31</MenuItem>
    <MenuItem className='menuItem' value={6}>+32</MenuItem>
    <MenuItem className='menuItem' value={7}>+33</MenuItem>
    <MenuItem className='menuItem' value={8}>+34</MenuItem>
    <MenuItem className='menuItem' value={9}>+36</MenuItem>
    <MenuItem className='menuItem' value={10}>+39</MenuItem>
    <MenuItem className='menuItem' value={11}>+40</MenuItem>
    <MenuItem className='menuItem' value={12}>+41</MenuItem>
    <MenuItem className='menuItem' value={13}>+43</MenuItem>
    <MenuItem className='menuItem' value={14}>+44</MenuItem>
    <MenuItem className='menuItem' value={15}>+45</MenuItem>
    <MenuItem className='menuItem' value={16}>+46</MenuItem>
    <MenuItem className='menuItem' value={17}>+47</MenuItem>
    <MenuItem className='menuItem' value={18}>+48</MenuItem>
    <MenuItem className='menuItem' value={19}>+49</MenuItem>
    <MenuItem className='menuItem' value={20}>+51</MenuItem>
    <MenuItem className='menuItem' value={21}>+52</MenuItem>
    <MenuItem className='menuItem' value={22}>+53</MenuItem>
    <MenuItem className='menuItem' value={23}>+54</MenuItem>
    <MenuItem className='menuItem' value={24}>+55</MenuItem>
    <MenuItem className='menuItem' value={25}>+56</MenuItem>
    <MenuItem className='menuItem' value={26}>+57</MenuItem>
    <MenuItem className='menuItem' value={27}>+58</MenuItem>
    <MenuItem className='menuItem' value={28}>+60</MenuItem>
    <MenuItem className='menuItem' value={29}>+61</MenuItem>
    <MenuItem className='menuItem' value={30}>+62</MenuItem>
    <MenuItem className='menuItem' value={31}>+63</MenuItem>
    <MenuItem className='menuItem' value={32}>+64</MenuItem>
    <MenuItem className='menuItem' value={33}>+65</MenuItem>
    <MenuItem className='menuItem' value={34}>+66</MenuItem>
    <MenuItem className='menuItem' value={35}>+81</MenuItem>
    <MenuItem className='menuItem' value={36}>+82</MenuItem>
    <MenuItem className='menuItem' value={37}>+84</MenuItem>
    <MenuItem className='menuItem' value={38}>+86</MenuItem>
    <MenuItem className='menuItem' value={39}>+90</MenuItem>
    <MenuItem className='menuItem' value={40}>+91</MenuItem>
    <MenuItem className='menuItem' value={41}>+92</MenuItem>
    <MenuItem className='menuItem' value={42}>+93</MenuItem>
    <MenuItem className='menuItem' value={43}>+94</MenuItem>
    <MenuItem className='menuItem' value={44}>+95</MenuItem>
    <MenuItem className='menuItem' value={45}>+98</MenuItem>
    <MenuItem className='menuItem' value={46}>+211</MenuItem>
    <MenuItem className='menuItem' value={47}>+212</MenuItem>
    <MenuItem className='menuItem' value={48}>+213</MenuItem>
    <MenuItem className='menuItem' value={49}>+216</MenuItem>
    <MenuItem className='menuItem' value={50}>+218</MenuItem>
    <MenuItem className='menuItem' value={51}>+220</MenuItem>
    <MenuItem className='menuItem' value={52}>+221</MenuItem>
    <MenuItem className='menuItem' value={53}>+222</MenuItem>
    <MenuItem className='menuItem' value={54}>+223</MenuItem>
    <MenuItem className='menuItem' value={55}>+224</MenuItem>
    <MenuItem className='menuItem' value={56}>+225</MenuItem>
    <MenuItem className='menuItem' value={57}>+226</MenuItem>
    <MenuItem className='menuItem' value={58}>+227</MenuItem>
    <MenuItem className='menuItem' value={59}>+228</MenuItem>
    <MenuItem className='menuItem' value={60}>+229</MenuItem>
    <MenuItem className='menuItem' value={61}>+230</MenuItem>
    <MenuItem className='menuItem' value={62}>+231</MenuItem>
    <MenuItem className='menuItem' value={63}>+232</MenuItem>
    <MenuItem className='menuItem' value={64}>+233</MenuItem>
    <MenuItem className='menuItem' value={65}>+234</MenuItem>
    <MenuItem className='menuItem' value={66}>+235</MenuItem>
    <MenuItem className='menuItem' value={67}>+236</MenuItem>
    <MenuItem className='menuItem' value={68}>+237</MenuItem>
    <MenuItem className='menuItem' value={69}>+238</MenuItem>
    <MenuItem className='menuItem' value={70}>+239</MenuItem>
    <MenuItem className='menuItem' value={71}>+240</MenuItem>
    <MenuItem className='menuItem' value={72}>+241</MenuItem>
    <MenuItem className='menuItem' value={73}>+242</MenuItem>
    <MenuItem className='menuItem' value={74}>+243</MenuItem>
    <MenuItem className='menuItem' value={75}>+244</MenuItem>
    <MenuItem className='menuItem' value={76}>+245</MenuItem>
    <MenuItem className='menuItem' value={77}>+246</MenuItem>
    <MenuItem className='menuItem' value={78}>+248</MenuItem>
    <MenuItem className='menuItem' value={79}>+249</MenuItem>
    <MenuItem className='menuItem' value={80}>+250</MenuItem>
    <MenuItem className='menuItem' value={81}>+251</MenuItem>
    <MenuItem className='menuItem' value={82}>+252</MenuItem>
    <MenuItem className='menuItem' value={83}>+253</MenuItem>
    <MenuItem className='menuItem' value={84}>+254</MenuItem>
    <MenuItem className='menuItem' value={85}>+255</MenuItem>
    <MenuItem className='menuItem' value={86}>+256</MenuItem>
    <MenuItem className='menuItem' value={87}>+257</MenuItem>
    <MenuItem className='menuItem' value={88}>+258</MenuItem>
    <MenuItem className='menuItem' value={89}>+260</MenuItem>
    <MenuItem className='menuItem' value={90}>+261</MenuItem>
    <MenuItem className='menuItem' value={91}>+262</MenuItem>
    <MenuItem className='menuItem' value={92}>+263</MenuItem>
    <MenuItem className='menuItem' value={93}>+264</MenuItem>
    <MenuItem className='menuItem' value={94}>+265</MenuItem>
    <MenuItem className='menuItem' value={95}>+266</MenuItem>
    <MenuItem className='menuItem' value={96}>+267</MenuItem>
    <MenuItem className='menuItem' value={97}>+268</MenuItem>
    <MenuItem className='menuItem' value={98}>+269</MenuItem>
    <MenuItem className='menuItem' value={99}>+290</MenuItem>
    <MenuItem className='menuItem' value={100}>+291</MenuItem>
    <MenuItem className='menuItem' value={101}>+297</MenuItem>
    <MenuItem className='menuItem' value={102}>+298</MenuItem>
    <MenuItem className='menuItem' value={103}>+299</MenuItem>
    <MenuItem className='menuItem' value={104}>+350</MenuItem>
    <MenuItem className='menuItem' value={105}>+351</MenuItem>
    <MenuItem className='menuItem' value={106}>+352</MenuItem>
    <MenuItem className='menuItem' value={107}>+353</MenuItem>
    <MenuItem className='menuItem' value={108}>+354</MenuItem>
    <MenuItem className='menuItem' value={109}>+355</MenuItem>
    <MenuItem className='menuItem' value={110}>+356</MenuItem>
    <MenuItem className='menuItem' value={111}>+357</MenuItem>
    <MenuItem className='menuItem' value={112}>+358</MenuItem>
    <MenuItem className='menuItem' value={113}>+359</MenuItem>
    <MenuItem className='menuItem' value={114}>+370</MenuItem>
    <MenuItem className='menuItem' value={115}>+371</MenuItem>
    <MenuItem className='menuItem' value={116}>+372</MenuItem>
    <MenuItem className='menuItem' value={117}>+373</MenuItem>
    <MenuItem className='menuItem' value={118}>+374</MenuItem>
    <MenuItem className='menuItem' value={119}>+375</MenuItem>
    <MenuItem className='menuItem' value={120}>+376</MenuItem>
    <MenuItem className='menuItem' value={121}>+377</MenuItem>
    <MenuItem className='menuItem' value={122}>+378</MenuItem>
    <MenuItem className='menuItem' value={123}>+380</MenuItem>
    <MenuItem className='menuItem' value={124}>+381</MenuItem>
    <MenuItem className='menuItem' value={125}>+382</MenuItem>
    <MenuItem className='menuItem' value={126}>+385</MenuItem>
    <MenuItem className='menuItem' value={127}>+386</MenuItem>
    <MenuItem className='menuItem' value={128}>+387</MenuItem>
    <MenuItem className='menuItem' value={129}>+389</MenuItem>
    <MenuItem className='menuItem' value={130}>+420</MenuItem>
    <MenuItem className='menuItem' value={131}>+421</MenuItem>
    <MenuItem className='menuItem' value={132}>+423</MenuItem>
    <MenuItem className='menuItem' value={133}>+500</MenuItem>
    <MenuItem className='menuItem' value={134}>+501</MenuItem>
    <MenuItem className='menuItem' value={135}>+502</MenuItem>
    <MenuItem className='menuItem' value={136}>+503</MenuItem>
    <MenuItem className='menuItem' value={137}>+504</MenuItem>
    <MenuItem className='menuItem' value={138}>+505</MenuItem>
    <MenuItem className='menuItem' value={139}>+506</MenuItem>
    <MenuItem className='menuItem' value={140}>+507</MenuItem>
    <MenuItem className='menuItem' value={141}>+508</MenuItem>
    <MenuItem className='menuItem' value={142}>+509</MenuItem>
    <MenuItem className='menuItem' value={143}>+590</MenuItem>
    <MenuItem className='menuItem' value={144}>+591</MenuItem>
    <MenuItem className='menuItem' value={145}>+592</MenuItem>
    <MenuItem className='menuItem' value={146}>+593</MenuItem>
    <MenuItem className='menuItem' value={147}>+594</MenuItem>
    <MenuItem className='menuItem' value={148}>+595</MenuItem>
    <MenuItem className='menuItem' value={149}>+596</MenuItem>
    <MenuItem className='menuItem' value={150}>+597</MenuItem>
    <MenuItem className='menuItem' value={151}>+598</MenuItem>
    <MenuItem className='menuItem' value={152}>+599</MenuItem>
    <MenuItem className='menuItem' value={153}>+670</MenuItem>
    <MenuItem className='menuItem' value={154}>+672</MenuItem>
    <MenuItem className='menuItem' value={155}>+673</MenuItem>
    <MenuItem className='menuItem' value={156}>+674</MenuItem>
    <MenuItem className='menuItem' value={157}>+675</MenuItem>
    <MenuItem className='menuItem' value={158}>+676</MenuItem>
    <MenuItem className='menuItem' value={159}>+677</MenuItem>
    <MenuItem className='menuItem' value={160}>+678</MenuItem>
    <MenuItem className='menuItem' value={161}>+679</MenuItem>
    <MenuItem className='menuItem' value={162}>+680</MenuItem>
    <MenuItem className='menuItem' value={163}>+681</MenuItem>
    <MenuItem className='menuItem' value={164}>+682</MenuItem>
    <MenuItem className='menuItem' value={165}>+683</MenuItem>
    <MenuItem className='menuItem' value={166}>+685</MenuItem>
    <MenuItem className='menuItem' value={167}>+686</MenuItem>
    <MenuItem className='menuItem' value={168}>+687</MenuItem>
    <MenuItem className='menuItem' value={169}>+688</MenuItem>
    <MenuItem className='menuItem' value={170}>+689</MenuItem>
    <MenuItem className='menuItem' value={171}>+690</MenuItem>
    <MenuItem className='menuItem' value={172}>+691</MenuItem>
    <MenuItem className='menuItem' value={173}>+692</MenuItem>
    <MenuItem className='menuItem' value={174}>+850</MenuItem>
    <MenuItem className='menuItem' value={175}>+852</MenuItem>
    <MenuItem className='menuItem' value={176}>+853</MenuItem>
    <MenuItem className='menuItem' value={177}>+855</MenuItem>
    <MenuItem className='menuItem' value={178}>+856</MenuItem>
    <MenuItem className='menuItem' value={179}>+870</MenuItem>
    <MenuItem className='menuItem' value={180}>+880</MenuItem>
    <MenuItem className='menuItem' value={181}>+886</MenuItem>
    <MenuItem className='menuItem' value={182}>+960</MenuItem>
    <MenuItem className='menuItem' value={183}>+961</MenuItem>
    <MenuItem className='menuItem' value={184}>+962</MenuItem>
    <MenuItem className='menuItem' value={185}>+963</MenuItem>
    <MenuItem className='menuItem' value={186}>+964</MenuItem>
    <MenuItem className='menuItem' value={187}>+965</MenuItem>
    <MenuItem className='menuItem' value={188}>+966</MenuItem>
    <MenuItem className='menuItem' value={189}>+967</MenuItem>
    <MenuItem className='menuItem' value={190}>+968</MenuItem>
    <MenuItem className='menuItem' value={191}>+970</MenuItem>
    <MenuItem className='menuItem' value={192}>+971</MenuItem>
    <MenuItem className='menuItem' value={193}>+972</MenuItem>
    <MenuItem className='menuItem' value={194}>+973</MenuItem>
    <MenuItem className='menuItem' value={195}>+974</MenuItem>
    <MenuItem className='menuItem' value={196}>+975</MenuItem>
    <MenuItem className='menuItem' value={197}>+976</MenuItem>
    <MenuItem className='menuItem' value={198}>+977</MenuItem>
    <MenuItem className='menuItem' value={199}>+992</MenuItem>
    <MenuItem className='menuItem' value={200}>+993</MenuItem>
    <MenuItem className='menuItem' value={201}>+994</MenuItem>
    <MenuItem className='menuItem' value={202}>+995</MenuItem>
    <MenuItem className='menuItem' value={203}>+996</MenuItem>
    <MenuItem className='menuItem' value={204}>+998</MenuItem>
    <MenuItem className='menuItem' value={205}>+1-242</MenuItem>
    <MenuItem className='menuItem' value={206}>+1-246</MenuItem>
    <MenuItem className='menuItem' value={207}>+1-264</MenuItem>
    <MenuItem className='menuItem' value={208}>+1-268</MenuItem>
    <MenuItem className='menuItem' value={209}>+1-284</MenuItem>
    <MenuItem className='menuItem' value={210}>+1-340</MenuItem>
    <MenuItem className='menuItem' value={211}>+1-345</MenuItem>
    <MenuItem className='menuItem' value={212}>+1-441</MenuItem>
    <MenuItem className='menuItem' value={213}>+1-473</MenuItem>
    <MenuItem className='menuItem' value={214}>+1-649</MenuItem>
    <MenuItem className='menuItem' value={215}>+1-664</MenuItem>
    <MenuItem className='menuItem' value={216}>+1-670</MenuItem>
    <MenuItem className='menuItem' value={217}>+1-671</MenuItem>
    <MenuItem className='menuItem' value={218}>+1-684</MenuItem>
    <MenuItem className='menuItem' value={219}>+1-721</MenuItem>
    <MenuItem className='menuItem' value={220}>+1-758</MenuItem>
    <MenuItem className='menuItem' value={221}>+1-767</MenuItem>
    <MenuItem className='menuItem' value={222}>+1-784</MenuItem>
    <MenuItem className='menuItem' value={223}>+1-809,1-829,1-849</MenuItem>
    <MenuItem className='menuItem' value={224}>+1-868</MenuItem>
    <MenuItem className='menuItem' value={225}>+1-869</MenuItem>
    <MenuItem className='menuItem' value={226}>+1-876</MenuItem>
    <MenuItem className='menuItem' value={227}>+39-06</MenuItem>
    <MenuItem className='menuItem' value={228}>+Â </MenuItem>
  </div>
}